name: kiss_graph_example
description: Example server implementation using the kiss_graph library
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Use the local kiss_graph library
  kiss_graph:
    path: ../
  
  # Web framework for the example server
  shelf_plus: ^1.6.0

dev_dependencies:
  build_runner: ^2.4.7
  test: ^1.24.0
  very_good_analysis: ^9.0.0 
