targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      openapi_code_builder:
        options:
          input_spec: lib/graph-node-api.openapi.yaml