name: kiss_graph
description: A reusable library for managing graph-based nodes with spatial queries and path tracing, featuring dependency injection support
version: 0.1.0
homepage: https://github.com/WAMF/kiss_graph
repository: https://github.com/WAMF/kiss_graph
issue_tracker: https://github.com/WAMF/kiss_graph/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  kiss: ^0.0.1
  kiss_repository: ^0.11.0
  meta: ^1.12.0
  openapi_base: ^2.0.0
  shelf_plus: ^1.6.0
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  openapi_code_builder: ^1.6.0+2
  test: ^1.24.0
  very_good_analysis: ^9.0.0
