name: kiss_graph
description: A microservice for managing graph-based nodes with spatial queries and path tracing
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf_plus: ^1.6.0
  kiss_repository: ^0.11.0
  kiss: ^0.0.1
  json_annotation: ^4.8.1
  uuid: ^4.1.0
  freezed_annotation: ^3.1.0
  very_good_analysis: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  openapi_code_builder: ^1.6.0+2
  test: ^1.24.0